name: Docker Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  REGISTRY: ghcr.io
  IMAGE_CACHE_TAG: ghcr.io/mnonnenmacher/ort:cache
  IMAGE_NAME: ghcr.io/mnonnenmacher/ort

jobs:
  disk_space:
    name: Disk Space
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print Disk Space
        run: |
          df -h
      - name: List Docker Images
        run: |
          docker images
      - name: Remove Unneeded Docker Images
        run: |
          docker image rm node:16 node:16-alpine node:18 node:18-alpine node:20 node:20-alpine debian:10 debian:11 ubuntu:20.04 ubuntu:22.04
      - name: Print Disk Space
        run: |
          df -h
      - name: Get Size of Installed Tools
        if: ${{ false }} # Can be enabled if the 'Remove Tools' step below needs to be updated.
        run: |
          sudo du -hsc /usr/lib/*
          sudo du -hsc /usr/local/*
          sudo du -hsc /usr/local/lib/*
          sudo du -hsc /usr/local/share/*
          sudo du -hsc /usr/share/*
      - name: Remove Unneeded Tools
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/az_11.3.1
          sudo rm -rf /usr/share/dotnet
          #sudo rm -rf /usr/share/gradle-8.7
          sudo rm -rf /usr/share/kotlinc
          sudo rm -rf /usr/share/mecab
          sudo rm -rf /usr/share/miniconda
          sudo rm -rf /usr/share/ri
          sudo rm -rf /usr/share/sbt
          sudo rm -rf /usr/share/swift
      - name: Print Disk Space
        run: |
          df -h
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Get ORT version
        run: |
          ORT_VERSION=$(./gradlew -q properties --property version | sed -nr "s/version: (.+)/\1/p")
          echo "ORT_VERSION=${ORT_VERSION}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=pep440,pattern={{version}}
            type=raw,value=${{ env.ORT_VERSION }}
            type=ref,event=branch
            type=ref,event=tag
      - name: Build & Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.IMAGE_CACHE_TAG }},mode=max
      - name: Print Disk Space
        run: |
          df -h
